spring:
  application:
    name: ${SPRING_APP_NAME:identity-recognition-process}
  data:
    mongodb:
      uri: ${MONGO_URI}

gemini:
  ia:
    model: ${GEMINI_MODEL}
    api:
      key: ${GEMINI_API_KEY}

spring.cloud.stream:
  function:
    - registerIdentity
  bindings:
    identity-out-0:
      destination: ${TOPIC_REGISTER_IDENTITY:register-identity}
      contentType: application/json
      producer:
        useNativeEncoding: false
  kafka:
    binder:
      brokers: ${KAFKA_BROKER}
      autoCreateTopics: true
      configuration:
        allow.auto.create.topics: true
        auto.offset.reset: earliest
        sasl.mechanism: PLAIN
        sasl.jaas.config: ${KAFKA_JAAS_CONFIG}
  instanceCount: 1
  instanceIndex: 0
  bindingRetryInterval: 10

identity:
  service:
    url: ${IDENTITY_SERVICE_URL:http://localhost:9090}

